# varx=300-123
# vary=int(input("enter the number"))
# if varx==vary:
#     print("Equal")
# else:
#     print("Not Equal")


# sweet=int(input("enter the number:-"))
# if sweet%3==0: 
#     print("choco")
# elif sweet%7==0:
#     print("late")
# else:
#     print("chocolate")


num=int(input("enter the number:-"))
number=44*30
if num>=number:
    print("greater than equal to")
else:
    print("lesser")


