# vowel=input("enter the letter :-")
# if vowel=="a" or vowel=="e" or vowel=="i" or vowel=="o" or vowel=="u":
#     print("vowel")
# else:
#     print("consonan")



# i=0
# n=input("enter the Name:-")
# while i<len(n):
#     if n[i]=="a"or n[i]=="e"or n[i]=="i"or n[i]=="o"or n[i]=="u":
#         print(n[i],"vowel")
#     else:
#         print(n[i],"constanant")
#     i=i+1




# string1=input("Enter your string-----------")
# if string1[-3:]=="ing":
#     m=string1.replace("ing","ly")
#     print(m)
# elif string1[-2:]=="ly":
#     print(string1)
# else:
#     if string1[-3:]!="ing":
#         print(string1+"ing")

